services:
  seafile-db:
    image: mariadb:10.6
    container_name: seafile-db
    restart: unless-stopped
    labels:
      yantr.app: "seafile"
      yantr.service: "Database"
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
      MYSQL_DATABASE: "seafile"
      MYSQL_USER: "seafile"
      MYSQL_PASSWORD: "changeme"
    volumes:
      - seafile_db:/var/lib/mysql

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    restart: unless-stopped
    labels:
      yantr.app: "seafile"
      yantr.service: "Web UI"
    depends_on:
      - seafile-db
    ports:
      - "8002"
    environment:
      SEAFILE_SERVER_LETSENCRYPT: "false"
      SEAFILE_SERVER_HOSTNAME: "localhost"
      DB_HOST: "seafile-db"
      DB_ROOT_PASSWD: "changeme"
      MYSQL_ROOT_PASSWORD: "changeme"
      MYSQL_HOST: "seafile-db"
      MYSQL_PORT: "3306"
      MYSQL_USER: "seafile"
      MYSQL_PASSWORD: "changeme"
      SEAFILE_ADMIN_EMAIL: "admin@example.com"
      SEAFILE_ADMIN_PASSWORD: "changeme"
    volumes:
      - seafile_data:/shared

volumes:
  seafile_db:
  seafile_data:
