services:
  tor:
    image: containers.torproject.org/tpo/onion-services/onimages/tor:alpine
    container_name: cashu-me-tor
    labels:
      yantr.app: "cashu-me"
      yantr.service: "Tor Onion Service"
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - cashu-me
    volumes:
      - tor-keys:/var/lib/tor
      - ./torrc:/etc/tor/torrc:ro

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashu-me
    labels:
      yantr.app: "cashu-me"
      yantr.service: "Web UI"
    restart: unless-stopped
    networks:
      - cashu-me
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "3000:80"

networks:
  cashu-me:

volumes:
  tor-keys:
